const mongoose = require("mongoose");

// A single-use, 30-second QR token generated by outlet staff. Both sides of
// the loyalty loop are staff-initiated and use this same model:
//
//   earn   — staff enters the bill, customer scans, points are awarded
//   redeem — staff opens redemption, customer scans and picks a reward
//
// Staff-initiated in both directions is deliberate: a customer can never
// mint a token, so they can never award themselves points or spend points
// without someone at the counter.
const DynamicQRTokenSchema = new mongoose.Schema({
  organizationId: { type: mongoose.Schema.Types.ObjectId, ref: "Organization", required: true },
  token: { type: String, required: true, unique: true },
  generatedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  isUsed: { type: Boolean, default: false },

  purpose: { type: String, enum: ["earn", "redeem"], default: "earn" },

  // The bill the customer paid, in rupees. REQUIRED for an earn token and
  // enforced in pointsService, not here: the points award is a function of
  // this number, so an earn token without one could only award zero. Always
  // null on a redeem token.
  billAmount: { type: Number, default: null },

  // Which staff member identified themselves via PIN when this token was
  // generated. Null for a PIN-less outlet. Carried forward onto
  // PendingClaim/PointsTransaction — the attribution is decided at the
  // counter but written at the ledger, minutes apart on the earn path, and
  // this is one of the two artifacts that already bridge that gap (see
  // generatedBy above).
  performedByUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null },
  performedByName: { type: String, default: "" },

  createdAt: { type: Date, default: Date.now }
});

DynamicQRTokenSchema.index({ createdAt: 1 }, { expireAfterSeconds: 30 });

module.exports = mongoose.model("DynamicQRToken", DynamicQRTokenSchema);
